[versions]
agp = "8.7.3"
kotlin = "1.9.22"
compose-compiler = "1.5.4"
compose-bom = "2024.01.00"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }

